import domTestingLibraryCode from "./dom-testling-library.code.js";
import MagicString from "magic-string";
import { Runner } from "./test-runner.js";

function isTransformed(code) {
    return (/generated by Svelte/).test(code);
}
/**
 * @param {{}} [options]
 * @returns {import("vite").Plugin}
 */
export default function sveltekitPluginTest(options = {}) {
    const { playwright = {} } = options;
    /** @type {import("vite").ResolvedConfig} */
    let config;
    /** @type {import("vite").ViteDevServer} */
    let server;
    return {
        name: "sveltekit-plugin-test",
        apply: "serve",
        configResolved(_config) {
            config = _config;
        },
        configureServer(_server) {
            server = _server;
            const protocol = config.server.https ? "https" : "http";
            const port = config.server.port || 3000;
            playwright.use = {
                ...playwright.use,
                baseURL: `${protocol}://localhost:${port}`,
            };

            const runner = new Runner();
            server.httpServer?.once("listening", async () => {
                await runner.run();
            });
            server.watcher?.on("all", async () => {
                if (runner.isRunning) {
                    await runner.teardown();
                }
                await runner.run();
            });
        },
        async transform(code, id) {
            if (!id.endsWith(".svelte") || !isTransformed(code)) return;
            if (id.endsWith("generated/root.svelte")) {
                const magicString = new MagicString(code);
                magicString.append(`\n;console.log("ttt");\n${domTestingLibraryCode}`);
                return {
                    code: magicString.toString(),
                    map: magicString.generateMap(),
                };
            }
        }
    };
}
